import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { existsSync, mkdirSync, copyFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Deploy artifacts into a vault's plugin folder after every successful build
// (dev watch rebuilds included). Defaults to the git-ignored dev scratch vault
// in this repo — NEVER a real user vault (real vaults run the published store
// build). Override the target vault root with LAZY_CAMPAIGN_VAULT.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)));
const VAULT = process.env.LAZY_CAMPAIGN_VAULT || join(REPO_ROOT, "dev-vault");
const PLUGIN_DIR = join(VAULT, ".obsidian", "plugins", "lazy-campaign");
const ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

const deployPlugin = {
  name: "deploy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return; // don't deploy a broken build
      try {
        if (!existsSync(PLUGIN_DIR)) mkdirSync(PLUGIN_DIR, { recursive: true });
        for (const file of ARTIFACTS) {
          if (existsSync(file)) copyFileSync(file, join(PLUGIN_DIR, file));
        }
        console.log(`[deploy] artifacts -> ${PLUGIN_DIR}`);
      } catch (e) {
        console.warn(`[deploy] skipped: ${e.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [deployPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
