// Pure — no `obsidian` import. The seven "General-Use Combat Stat Blocks"
// from the Lazy GM's 5e Monster Builder Resource Document (CC-BY 4.0 — see
// `attribution.ts`). Each preset carries lean build fields (frontmatter) plus
// the full verbatim stat block as body markdown — ability arrays, saves,
// skills, and multiattack detail deliberately stay in the body, not the
// frontmatter (SCHEMA.md keeps the monster note's frontmatter lean).
// `usage` is the doc's guidance line on when the stat block works as a boss,
// elite, one-on-one, or group foe. Ids are stable forever.

import type { MonsterBuildFields } from "../dnd5e/monster-schema";

export interface MonsterPreset {
	id: string;
	name: string;
	cr: number;
	/** Doc's one-line usage guidance (boss/elite/one-on-one/groups). */
	usage: string;
	build: MonsterBuildFields;
	/** Verbatim full stat block, markdown (goes into the note body). */
	body: string;
}

function statBlock(lines: string[]): string {
	return lines.join("\n");
}

export const GENERAL_USE_MONSTERS: readonly MonsterPreset[] = [
	{
		id: "minion",
		name: "Minion",
		cr: 0.125,
		usage: "One-on-one against 1st-level characters, or in large groups at 4th level and above. Dexterity-focused.",
		build: {
			cr: 0.125,
			flavor: "Small or Medium creature",
			ac: 11,
			dc: 11,
			hp: 9,
			profBonus: 3,
			attacks: 1,
			damagePerAttack: 4,
			damageDice: "1d6 + 1",
			abilities: ["dex"],
			features: [],
			template: "minion",
		},
		body: statBlock([
			"**Armor Class** 11",
			"**Hit Points** 9 (2d8)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 10 (+0) | 12 (+1) | 10 (+0) | 10 (+0) | 12 (+1) | 10 (+0) |",
			"",
			"**Senses** passive Perception 11",
			"**Challenge** 1/8 (25 XP) · **Proficiency Bonus** +2",
			"",
			"**Actions**",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +3 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 4 (1d6 + 1) damage.",
		]),
	},
	{
		id: "soldier",
		name: "Soldier",
		cr: 0.5,
		usage: "Boss at 1st level, elite foe for two 2nd-level characters, one-on-one at 4th level, or in large groups at 6th level and above. Strength-focused.",
		build: {
			cr: 0.5,
			flavor: "Medium creature",
			ac: 12,
			dc: 12,
			hp: 22,
			profBonus: 4,
			attacks: 1,
			damagePerAttack: 8,
			damageDice: "1d12 + 2",
			abilities: ["str"],
			features: [],
			template: "soldier",
		},
		body: statBlock([
			"**Armor Class** 12 (leather armor or natural armor)",
			"**Hit Points** 22 (4d8 + 4)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 14 (+2) | 12 (+1) | 12 (+1) | 10 (+0) | 10 (+0) | 10 (+0) |",
			"",
			"**Senses** passive Perception 10",
			"**Challenge** 1/2 (100 XP) · **Proficiency Bonus** +2",
			"",
			"**Actions**",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +4 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 8 (1d12 + 2) damage.",
		]),
	},
	{
		id: "brute",
		name: "Brute",
		cr: 2,
		usage: "Boss against 2nd-level characters, elite foe against two 4th-level characters, one-on-one at 5th level, or in large groups at 10th level. Strength-focused.",
		build: {
			cr: 2,
			flavor: "Medium or Large creature",
			ac: 13,
			dc: 13,
			hp: 45,
			profBonus: 5,
			attacks: 2,
			damagePerAttack: 9,
			damageDice: "1d12 + 3",
			abilities: ["str", "con"],
			features: [],
			template: "brute",
		},
		body: statBlock([
			"**Armor Class** 13 (studded leather or natural armor)",
			"**Hit Points** 45 (7d8 + 14)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 16 (+3) | 12 (+1) | 14 (+2) | 10 (+0) | 10 (+0) | 8 (−1) |",
			"",
			"**Saving Throws** Con +4",
			"**Skills** Athletics +5",
			"**Senses** passive Perception 10",
			"**Challenge** 2 (450 XP) · **Proficiency Bonus** +2",
			"",
			"**Actions**",
			"",
			"***Multiattack.*** The brute makes two attacks.",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +5 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 9 (1d12 + 3) damage.",
		]),
	},
	{
		id: "specialist",
		name: "Specialist",
		cr: 4,
		usage: "Boss for 4th-level characters, elite opponent versus two 5th-level characters, one-on-one for 10th-level characters, or in large groups against 16th-level characters. Dexterity-focused.",
		build: {
			cr: 4,
			flavor: "Medium creature",
			ac: 14,
			dc: 14,
			hp: 84,
			profBonus: 6,
			attacks: 2,
			damagePerAttack: 14,
			damageDice: "3d6 + 4",
			abilities: ["dex", "wis"],
			features: [],
			template: "specialist",
		},
		body: statBlock([
			"**Armor Class** 14",
			"**Hit Points** 84 (13d8 + 26)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 12 (+1) | 18 (+4) | 14 (+2) | 10 (+0) | 14 (+2) | 12 (+1) |",
			"",
			"**Saving Throws** Dex +6, Wis +4",
			"**Skills** Acrobatics +6, Perception +4, Stealth +6",
			"**Senses** passive Perception 14",
			"**Challenge** 4 (1,100 XP) · **Proficiency Bonus** +2",
			"",
			"**Actions**",
			"",
			"***Multiattack.*** The specialist makes two attacks.",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +6 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 14 (3d6 + 4) damage.",
		]),
	},
	{
		id: "myrmidon",
		name: "Myrmidon",
		cr: 7,
		usage: "Boss for 5th-level characters, elite combatant against two 7th-level characters, one-on-one against 14th-level characters, or in large groups against 20th-level characters. Intelligence-focused.",
		build: {
			cr: 7,
			flavor: "Medium or Large creature",
			ac: 15,
			dc: 15,
			hp: 130,
			profBonus: 7,
			attacks: 3,
			damagePerAttack: 17,
			damageDice: "3d8 + 4",
			abilities: ["int", "dex", "wis"],
			features: [],
			template: "myrmidon",
		},
		body: statBlock([
			"**Armor Class** 15 (chain shirt or natural armor)",
			"**Hit Points** 130 (20d8 + 40)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 10 (+0) | 14 (+2) | 14 (+2) | 18 (+4) | 14 (+2) | 10 (+0) |",
			"",
			"**Saving Throws** Dex +5, Wis +5",
			"**Skills** Perception +5",
			"**Senses** passive Perception 15",
			"**Challenge** 7 (2,900 XP) · **Proficiency Bonus** +3",
			"",
			"**Actions**",
			"",
			"***Multiattack.*** The myrmidon makes three attacks.",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +7 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 17 (3d8 + 4) damage.",
		]),
	},
	{
		id: "sentinel",
		name: "Sentinel",
		cr: 11,
		usage: "Boss for 7th-level characters, elite foe against two 12th-level characters, or one-on-one against 16th-level characters. Strength-focused.",
		build: {
			cr: 11,
			flavor: "Medium, Large, or Huge creature",
			ac: 17,
			dc: 17,
			hp: 165,
			profBonus: 9,
			attacks: 4,
			damagePerAttack: 18,
			damageDice: "3d8 + 5",
			abilities: ["str", "dex"],
			features: [],
			template: "sentinel",
		},
		body: statBlock([
			"**Armor Class** 17 (natural armor or magical protection)",
			"**Hit Points** 165 (22d8 + 66)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 20 (+5) | 16 (+3) | 16 (+3) | 10 (+0) | 14 (+2) | 10 (+0) |",
			"",
			"**Saving Throws** Str +9, Dex +7",
			"**Skills** Perception +6",
			"**Senses** passive Perception 16",
			"**Challenge** 11 (7,200 XP) · **Proficiency Bonus** +4",
			"",
			"**Actions**",
			"",
			"***Multiattack.*** The sentinel makes four attacks.",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +9 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 18 (3d8 + 5) damage.",
		]),
	},
	{
		id: "champion",
		name: "Champion",
		cr: 15,
		usage: "Boss for 11th-level characters, elite foe for two 15th-level characters, or a one-on-one challenge against 17th-level characters. Charisma-focused.",
		build: {
			cr: 15,
			flavor: "Medium, Large, or Huge creature",
			ac: 19,
			dc: 19,
			hp: 212,
			profBonus: 11,
			attacks: 4,
			damagePerAttack: 24,
			damageDice: "4d8 + 6",
			abilities: ["cha", "wis"],
			features: [],
			template: "champion",
		},
		body: statBlock([
			"**Armor Class** 19 (natural armor or magical protection)",
			"**Hit Points** 212 (25d8 + 100)",
			"**Speed** 30 ft.",
			"",
			"| STR | DEX | CON | INT | WIS | CHA |",
			"| --- | --- | --- | --- | --- | --- |",
			"| 10 (+0) | 12 (+1) | 18 (+4) | 12 (+1) | 16 (+3) | 22 (+6) |",
			"",
			"**Saving Throws** Wis +8, Cha +11",
			"**Skills** Perception +8",
			"**Senses** passive Perception 18",
			"**Challenge** 15 (13,000 XP) · **Proficiency Bonus** +5",
			"",
			"**Actions**",
			"",
			"***Multiattack.*** The champion makes four attacks.",
			"",
			"***Attack.*** *Melee or Ranged Weapon Attack:* +11 to hit, reach 5 ft. or range 60 ft., one target. *Hit:* 24 (4d8 + 6) damage.",
		]),
	},
];
